version: '3.8'

services:
  calculatemoney:
    image: ${DOCKER_REGISTRY-}calculatemoney
    build: 
      context: .
      dockerfile: CalculateMoneyDockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "7185:8080"