version: '3.8'
services:
  authservice:
    build: 
      context: .
      dockerfile: AuthDockerfile
    ports:
      - "7178:7178"
    environment:
      - ConnectionStrings__Postgres=Host=localhost;Port=8080;Database=psql;Username=vlat;Password=12345"

  calculatemoney:
    build: 
      context: .
      dockerfile: CalcDockerfile
    ports:
      - "7185:7185"

  historyservice:
    build: 
      context: .
      dockerfile: HistoryDocekrfile
    ports:
      - "7002:7002"
    environment:
      - ConnectionStrings__Redis=localhost:6400

  db:
    image: postgres
    environment:
      - POSTGRES_USER=vlat
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=psql
    ports:
      - "8080:5432"

  redis:
    image: redis
    ports:
      - "6400:6379"